modLoader="javafml"
loaderVersion="[33,)"
license="GNU LGPL 3.0"

[[mods]]
    modId="wailaharvestability"
    version="${file.jarVersion}"
    displayName="Waila Harvestability"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/waila-harvestability-renewed"
    issueTrackerURL="https://github.com/embeddedt/WailaHarvestabilityRenewed/issues"
    authors="squeek, embeddedt"
    credits=""
    description='''
    An add-on for Waila that adds information about the harvestability of what you are looking at
    '''

[[dependencies.wailaharvestability]]
    modId="waila"
    mandatory=true
    versionRange="[1.10,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.wailaharvestability]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.wailaharvestability]]
    modId="tconstruct"
    mandatory=false
    versionRange="[3.3.4.336,)"
    ordering="AFTER"
    side="BOTH"
